"""DocumentGeneratorTool — Jinja2 → Markdown → PDF (WeasyPrint).

Renders a professional PDF report into ``reports/``:

1. The input sections are injected into a Jinja2 Markdown skeleton
   (title page header + operator metadata).
2. ``markdown`` converts to HTML with a compact embedded CSS stylesheet.
3. WeasyPrint renders the PDF (CPU-bound → ``asyncio.to_thread``).

The returned path is verified (file exists, non-empty, ``%PDF`` magic) before
the tool reports success — the Phase 6 test opens it with ``pypdf`` again.
Filenames are slug-sanitised; the intermediate ``.md`` is kept next to the
PDF for the dashboard's preview pane.
"""

from __future__ import annotations

import asyncio
import re
from datetime import UTC, datetime
from pathlib import Path
from typing import ClassVar, Literal

import markdown
from jinja2 import Environment
from pydantic import BaseModel, Field

from exceptions import ToolExecutionError
from tools.base import BaseToolInput, BaseToolOutput, EnergyForgeTool

REPORTS_DIR = Path(__file__).resolve().parent.parent / "reports"

_TEMPLATE = """\
---
title: "{{ title }}"
---

# {{ title }}

**Report type:** {{ report_type }} · **Generated:** {{ generated_at }} · **By:** EnergyForge Agent

{% if meta %}
| Field | Value |
|---|---|
{% for key, value in meta.items() %}| {{ key }} | {{ value }} |
{% endfor %}
{% endif %}

{% for section in sections %}
## {{ section.heading }}

{{ section.body }}

{% endfor %}
---
*Generated by EnergyForge Agent. Confidence figures are model-derived; verify critical decisions.*
"""

_CSS = """
@page { size: A4; margin: 2.2cm 1.8cm; @bottom-right { content: counter(page) " / " counter(pages);
        font-size: 8pt; color: #666; } }
body { font-family: 'Liberation Sans', 'DejaVu Sans', sans-serif; font-size: 10pt; color: #1a1a1a; }
h1 { color: #0b3d91; border-bottom: 2px solid #0b3d91; padding-bottom: 4px; }
h2 { color: #0b3d91; margin-top: 18px; }
table { border-collapse: collapse; width: 100%; margin: 8px 0; }
th, td { border: 1px solid #bbb; padding: 4px 8px; text-align: left; font-size: 9pt; }
th { background: #eef2f9; }
code { background: #f4f4f4; padding: 1px 4px; border-radius: 3px; }
blockquote { border-left: 3px solid #0b3d91; margin-left: 0; padding-left: 12px; color: #444; }
"""


class ReportSection(BaseModel):
    """One section of the report."""

    heading: str = Field(min_length=1, max_length=200)
    body: str = Field(description="Markdown content of the section")


class DocumentGeneratorInput(BaseToolInput):
    """Input for DocumentGeneratorTool."""

    report_type: Literal["incident", "maintenance", "executive", "compliance"] = Field(
        description="Report category"
    )
    title: str = Field(min_length=3, max_length=200)
    slug: str = Field(description="Filename slug, e.g. wt07-bearing-2026-07-22")
    sections: list[ReportSection] = Field(min_length=1)
    meta: dict[str, str] = Field(default_factory=dict,
                                 description="Key/value header table (asset id, severity, …)")


class DocumentGeneratorOutput(BaseToolOutput):
    """Generated artifact locations."""

    report_type: str = ""
    title: str = ""
    file_path: str = ""
    markdown_path: str = ""
    size_bytes: int = 0
    generated_at: str = ""


def _render_pdf(html: str, target: Path) -> None:
    from weasyprint import HTML

    HTML(string=html, base_url=".").write_pdf(target=target)


def _sanitise_slug(slug: str) -> str:
    cleaned = re.sub(r"[^a-z0-9\-_]+", "-", slug.strip().lower())
    cleaned = re.sub(r"-{2,}", "-", cleaned).strip("-")
    if not cleaned:
        raise ToolExecutionError("slug sanitised to empty string", tool_name="document_generator")
    return cleaned[:80]


class DocumentGeneratorTool(EnergyForgeTool[DocumentGeneratorInput, DocumentGeneratorOutput]):
    """Render a Markdown report to a professional PDF.

    Feed it structured sections (heading + Markdown body). Returns the
    absolute path of the verified PDF artifact under ``reports/``.
    """

    name: ClassVar[str] = "document_generator"
    description: ClassVar[str] = (
        "Render a report to PDF from structured Markdown sections "
        "(report_type: incident|maintenance|executive|compliance; title; slug; "
        "sections[{heading, body}]; optional meta table). Returns the path of "
        "the generated, verified PDF file."
    )
    input_model: ClassVar[type[BaseToolInput]] = DocumentGeneratorInput
    output_model: ClassVar[type[BaseToolOutput]] = DocumentGeneratorOutput

    async def _arun(self, tool_input: DocumentGeneratorInput) -> DocumentGeneratorOutput:
        slug = _sanitise_slug(tool_input.slug)
        stamp = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")
        REPORTS_DIR.mkdir(parents=True, exist_ok=True)
        pdf_path = (REPORTS_DIR / f"{slug}_{stamp}.pdf").resolve()
        md_path = pdf_path.with_suffix(".md")

        env = Environment(autoescape=False, trim_blocks=True, lstrip_blocks=True)
        markdown_text = env.from_string(_TEMPLATE).render(
            title=tool_input.title,
            report_type=tool_input.report_type,
            generated_at=stamp,
            sections=[s.model_dump() for s in tool_input.sections],
            meta=tool_input.meta,
        )
        md_path.write_text(markdown_text, encoding="utf-8")
        html = (
            f"<html><head><meta charset='utf-8'><style>{_CSS}</style></head><body>"
            f"{markdown.markdown(markdown_text, extensions=['tables', 'fenced_code'])}"
            "</body></html>"
        )

        await asyncio.to_thread(_render_pdf, html, pdf_path)

        if not pdf_path.exists() or pdf_path.stat().st_size == 0:
            raise ToolExecutionError("PDF render produced no output", tool_name=self.name)
        if pdf_path.read_bytes()[:5] != b"%PDF-":
            raise ToolExecutionError("generated file failed %PDF magic check", tool_name=self.name)

        return DocumentGeneratorOutput(
            report_type=tool_input.report_type,
            title=tool_input.title,
            file_path=str(pdf_path),
            markdown_path=str(md_path),
            size_bytes=pdf_path.stat().st_size,
            generated_at=stamp,
            confidence=0.97,
        )
